### ISSUE TITLE
Little problem with opencart and page cache.

### ISSUE THREAD

**Issue by ag462391** [budgetneon/v2pagecache#13]
The problem was found on the platform opencart 2.1.0.2.1

For the example - http://kosmetiko.in.ua/

Let the buyer clicked "Buy" button and then pressed the "Continue Shopping", instead of "Order" and then accidentally closed the page.

After the opening of the main page in the basket buyer sees the "0" of goods and by clicking on the basket the inscription "The basket is empty" Without the inclusion of a cache in a basket buyer will immediately see the goods.
 
Everything comes back to normal (the basket is updated with the previously added goods) after moving to any other page or click on the "Buy" button.

**Comment by ag462391** [comment]
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=19079 It works? Link does not work. Where can I download and try?

**Comment by budgetneon** [comment]
Opencart changed a lot of things in the various 2.x versions, including session handling, so people are having trouble with V2 pagecache.  That's why I took it down.

You can download the zip files from github, here: https://github.com/budgetneon/v2pagecache
(see the various ocmod.zip files)

We have no time at the moment to support them though, and as I said, people are having issues with the module and recent opencart 2.x versions.

**Comment by ag462391** [comment]
OK, everything is clear. Good luck to you!
