### ISSUE TITLE
Account page is cached

### ISSUE THREAD

**Issue by gags88** [budgetneon/v2pagecache#18]
Hi,

As i have gone through **v2pagecache.php** file and i have read that it does not cache `/account` pages. But It is being cached.

I can see comment in View source as below

> cache protocol [http] host [abc.com] device [desktop] uri [host [abc.com] uri [/account](en/INR) expires: 2016-10-19 00:09:07 Asia/Kolkata

And it created an issue while "Cancel" the order. Order was cancelled in backend but still showed "order placed". How can i avoid that?

Or shall i mention every URL in **v2pagecache.php** which does not need caching,

**Comment by budgetneon** [comment]
It shouldn't be caching any pages (or serving cached pages) if you're logged in to opencart.

It could cache a page with the uri of "/account" if you aren't logged in...which I assume would be okay, since the same content would be presented to any user not logged in.

Can you clarify if the cached page is being created (or served) when you're logged in?

> > And it created an issue while "Cancel" the order. Order was cancelled in backend but still showed "order placed". How can i avoid that?

What is the uri that was cached that should not have been in this case?

**Comment by gags88** [comment]
> `It could cache a page with the uri of "/account" if you aren't logged in...which I assume would be okay, since the same content would be presented to any user not logged in.`

That is what i am wondering, why my **abc.com/account** page has been cached with User logged into the Store. Very weird.

The Order cancel page was `abc.com/order-history` which also shall not be cached as user is already logged in.

And Moreover, _abc.com/account_ does not make sense if user has not logged in, he will be redirected to Login in anycase.

However, mentioning explicity `#/account#` and `#/order-history` seems to solve the issue but it is not working as you have mentioned in comments.

**Comment by budgetneon** [comment]
Okay, so your issue is more correctly:

"The pagecache is caching, and serving cached pages to logged in users".

Is that correct?

If so, can you tell me:
- What version of opencart
- What version of the pagecache
- What version of PHP
- What SAPI is being used (this is shown on the admin page for the cache)

The code is checking for logged in users, and we didn't see an issue like this when we tested.  The code checking if you're logged in is pretty straightforward:

https://github.com/budgetneon/v2pagecache/blob/master/oc22/upload/system/library/v2pagecache.php#L243

**Comment by gags88** [comment]
Yes, you gt it right.
- What version of opencart - **2.1**
- What version of the pagecach - **'2.8.19'**
- What version of PHP - **5.6.25**
- What SAPI is being used (this is shown on the admin page for the cache) - **cgi-fcgi**

Very weird, i cant even find **$this->GetSessionVar();** in my _v2pagecache.php_

**Comment by budgetneon** [comment]
> > Very weird, i cant even find $this->GetSessionVar(); in my v2pagecache.php

That's not good. Any way you can attach it here?  Did you download it from github, or from the opencart website?

**Comment by gags88** [comment]
Instead of
if( !empty($svar['customer_id']) || !empty($svar['affiliate_id'])) {
            $this->cacheable=false;
            return $this->cacheable;
        }  

I have
if(!empty($_SESSION['customer_id']) ||
            !empty($_SESSION['affiliate_id'])) {
            $this->cacheable=false;
            return $this->cacheable;
        }  

And, do you mean that if customer is logged in then no page will be cached at all??
I downloaded it from Opencart website

**Comment by budgetneon** [comment]
That's an old version of the pagecache. The current,and latest version of the pagecache is 1.1.9

Download the pagecache code again from either opencart's site or from github.  You have an old version.

**Comment by budgetneon** [comment]
Closing...customer is using an old version of the pagecache.

**Comment by gags88** [comment]
do you mean that if customer is logged in then no page will be cached at all or only account pages?
Will product pages be cahceD?

**Comment by budgetneon** [comment]
You are using an old version of the pagecache code with known bugs.

What it should do is NOT cache, or serve ANY cached pages to ANY customer that is logged in.

**Comment by budgetneon** [comment]
A pagecache cannot serve cached pages to a logged in user, because the content is different for every user (for example, if you're logged in, the html has the user name at the top, instead of a "login" link).

**Comment by gags88** [comment]
that is fine, but what about product pages??? that has lots of images and details

**Comment by budgetneon** [comment]
> > that is fine, but what about product pages???

Even product pages in opencart have html that is unique to every logged in user.  You can't cache content that's customized per logged in user.

**Comment by gags88** [comment]
Okayy!... Thanks :dancing_men:
