### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by alnux** [budgetneon/v2pagecache#21]
I download and install  " free page cache" but I have a problem when I clear entery cache  on v2 page cache (admin panel) and I try to go into my page by Mobil phone just show a blank page with the next message:

Fatal error: SessionHandler::create_sid(): Cannot call default session handler in Unknown on line 0

This just happening on smartphones because on pc does not show this issue

Thanks

Pd: I using openers 2.3.0.2 and the last version of v2pagecache

**Comment by budgetneon** [comment]
I assume that you're either

a) Using a third party theme that has a separate mobile theme...instead of just a responsive theme, like the stock opencart theme.

==or==

b) Using a specific mobile extension

Either way, the pagecache does have limited support for those.

See the documentation around settings, here: https://github.com/budgetneon/v2pagecache#settings

Specifically, the $cachebydevice setting.

If that doesn't help, there's probably nothing I can do...the pagecache is made and tested with the stock opencart theme, and that works fine with desktop and mobile because it's a single responsive output...not separate themes.    We can't test with all 3rd party themes and mobile extensions...it's too time consuming and expensive.

**Comment by alnux** [comment]
I did it with the stock theme, when I enable it and clear cache files by control panel and go to my page by smartphone show me the fatal error that I told you. I didn't change anything on config file of extension

**Comment by alnux** [comment]
I go to the link that you told but there is nothing

**Comment by budgetneon** [comment]
When I go to https://superlicor.com/, it fails not just for mobile, but for desktop as well.

The error "Fatal error: SessionHandler::create_sid(): Cannot call default session handler in Unknown on line 0" isn't helping me much.   It doesn't show which file or which line.

There's not enough info for me to help you, sorry.

**Comment by budgetneon** [comment]
I went to https://superlicor.com/login, and got this:

Parse error: syntax error, unexpected ';' in /home/superlic/public_html/system/library/v2pagecache.php on line 56

So, did you change something on line 56 and add an unexpected semicolon?   In the v2pagecache source code, there is no semicolon on line 56.

**Comment by budgetneon** [comment]
It seems to be working now, I assume you removed the change you made.

Just FYI, it's not really nice that you would make your own changes and then have me spend time diagnosing the problems it created.

**Comment by alnux** [comment]
sorry i was looking for a fix, becouse there was an error on session as i told you, but dont worry i find a fix. i dont know if its a singular problem or general but hidden problem. as i said when i clear page cache with the button "clear entery cache" and as soon as goto my smarthphone an try to load the page show me the fatal error about the sessionhandler. rigth now i fix it and fork the proyect and commit the changes. sorry if you feel loosing time that not was my intention.
