### ISSUE TITLE
do not cache category page

### ISSUE THREAD

**Issue by motaby** [budgetneon/v2pagecache#7]
Hi! v2pagecache should cache the category page? at my site module caches only home page and products

**Comment by budgetneon** [comment]
Yes, it should cache category pages.

But, if you have installed modules, or a 3rd party theme, there are things that will keep pages from being cached.

For example, it won't cache urls with patterns that match the $skip_urls settings.  It also won't return cached pages if you're logged in, or have items in the cart, etc.

**Comment by motaby** [comment]
yes, i have installed modules, and a 3rd party theme
but another module super page cache works ok
how to get to work with mega filter?

**Comment by budgetneon** [comment]
I assume "Super Page Cache" initially had issues with mega filter as well.   Because it's a paid module, the author had the time and money to go out and buy "mega filter" and figure out what the conflict was.

This is a free module, and we don't have the time and money to troubleshoot compatibility with all of the popular 3rd party modules.

You could try, however, adding   '#module/mega_filter#' to the $skip_urls setting.  That may fix at least one problem.

**Comment by motaby** [comment]
great! it works! thnx
